import logging
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session

from app.core.db import get_db_session
from app.core.dependencies import get_current_user
from app.modules.iam.domain.principal import AuthenticatedUser
from app.modules.runbooks.api.schemas import (
    RunbookDeleteResponse,
    RunbookGenerateRequest,
    RunbookListItem,
    RunbookListResponse,
    RunbookResponse,
)
from app.modules.runbooks.application.services import (
    delete_runbook,
    generate_runbook_task,
    get_runbook_by_id,
    list_runbooks,
)
from app.shared.openapi_helpers import DELETE_RESPONSES, LIST_RESPONSES, MUTATE_RESPONSES

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/runbooks", tags=["runbooks"])


def _build_runbook_response(runbook) -> RunbookResponse:
    return RunbookResponse(
        runbook_id=runbook.id,
        title=runbook.title,
        purpose=runbook.purpose,
        document_ids=[UUID(did) for did in runbook.document_ids],
        content=runbook.content,
        status=runbook.status,
        error_message=runbook.error_message,
        created_by=runbook.created_by,
        created_at=runbook.created_at,
        modified_date=runbook.modified_date,
    )


@router.post(
    "/generate",
    response_model=RunbookResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a structured markdown runbook from vectorized documents",
    description=(
        "Synthesises a markdown runbook from the specified set of documents using "
        "a specific purpose template.  The purpose drives the structure and tone "
        "of the generated output.\n\n"
        "Supported purposes: onboarding, incident_response, deployment, "
        "troubleshooting, training, and other.\n\n"
        "**Requires authentication** (any authenticated user can use this endpoint)."
    ),
    response_description="The generated runbook with full content",
    responses={
        401: {"description": "Missing or invalid authentication credentials"},
        500: {"description": "Runbook generation failed"},
        **MUTATE_RESPONSES,
    },
)
async def generate_runbook(
    request: RunbookGenerateRequest,
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    session: Annotated[Session, Depends(get_db_session)],
) -> RunbookResponse:
    runbook = await generate_runbook_task(
        session,
        document_ids=request.document_ids,
        purpose=request.purpose.value,
        title=request.title,
        user_id=current_user.id,
    )
    return _build_runbook_response(runbook)


@router.get(
    "",
    response_model=RunbookListResponse,
    status_code=status.HTTP_200_OK,
    summary="List generated runbooks",
    description=(
        "Returns a paginated list of runbooks generated by the authenticated user.  "
        "Results are scoped to the requesting user for privacy."
    ),
    response_description="Paginated list of runbook summaries",
    responses=LIST_RESPONSES,
)
def list_generated_runbooks(
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    session: Annotated[Session, Depends(get_db_session)],
    page: int = 1,
    page_size: int = 20,
) -> RunbookListResponse:
    if page < 1:
        page = 1
    if page_size < 1:
        page_size = 1
    if page_size > 100:
        page_size = 100

    runbooks, total = list_runbooks(
        session,
        page=page,
        page_size=page_size,
        created_by=current_user.id,
    )

    return RunbookListResponse(
        items=[
            RunbookListItem(
                runbook_id=rb.id,
                title=rb.title,
                purpose=rb.purpose,
                document_ids=[UUID(did) for did in rb.document_ids],
                status=rb.status,
                created_by=rb.created_by,
                created_at=rb.created_at,
            )
            for rb in runbooks
        ],
        total=total,
        page=page,
        page_size=page_size,
    )


@router.get(
    "/{runbook_id}",
    response_model=RunbookResponse,
    status_code=status.HTTP_200_OK,
    summary="Get details of a runbook",
    description=(
        "Returns the full content and metadata of a specific runbook by its UUID.  "
        "Includes the generated markdown content and the list of source documents."
    ),
    response_description="Full runbook with generated content",
    responses={
        404: {"description": "Runbook not found"},
        **LIST_RESPONSES,
    },
)
def get_runbook(
    runbook_id: UUID,
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    session: Annotated[Session, Depends(get_db_session)],
) -> RunbookResponse:
    runbook = get_runbook_by_id(session, runbook_id)
    return _build_runbook_response(runbook)


@router.delete(
    "/{runbook_id}",
    response_model=RunbookDeleteResponse,
    status_code=status.HTTP_200_OK,
    summary="Delete a runbook",
    description=(
        "Permanently deletes a runbook from the database.  "
        "The generated content is removed and cannot be recovered."
    ),
    response_description="Confirmation that the runbook was deleted",
    responses={
        404: {"description": "Runbook not found"},
        **DELETE_RESPONSES,
    },
)
def remove_runbook(
    runbook_id: UUID,
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    session: Annotated[Session, Depends(get_db_session)],
) -> RunbookDeleteResponse:
    delete_runbook(session, runbook_id)
    return RunbookDeleteResponse(detail="Runbook deleted successfully")
